-- ── LootCouncil EX — Data/BiS.lua ────────────────────────────────────────────
-- SHIPPED STATIC DATA — class → spec → phase → slot → {itemIDs}. GENERATED by
-- tools/build_data.lua from tools/sources/bis.csv — DO NOT EDIT BY HAND.
--
-- Shape (PROJECT.md §6.6): BiS[CLASS][spec][phase][slot] = { itemID, altID, ... }.

local LCEX = LootCouncilEX

LCEX.BiS = {
    ["MAGE"] = {
        ["Fire"] = {
            ["P2"] = {
                head = { 28830 },
                neck = { 29918 },
                hands = { 30055 },
            },
        },
        ["Frost"] = {
            ["P2"] = {
                head = { 28830 },
                neck = { 29918 },
            },
        },
    },
}
