-- ── LootCouncil EX — Data/Loot.lua ───────────────────────────────────────────
-- SHIPPED STATIC DATA — phase → raid → boss → {itemIDs}. GENERATED by tools/build_data.lua
-- from tools/sources/loot.csv — DO NOT EDIT BY HAND (your edits will be overwritten); edit
-- the CSV and re-run the converter.
--
-- Shape (PROJECT.md §6.6): Loot[phase].raids[raid][boss] = { itemID, ... }. Each raid also
-- carries an `_order` array giving boss kill order, honored by the DataAPI accessors.

local LCEX = LootCouncilEX

LCEX.Loot = {
    ["P2"] = {
        raids = {
            ["Serpentshrine Cavern"] = {
                _order = { "Hydross the Unstable", "The Lurker Below", "Leotheras the Blind", "Fathom-Lord Karathress", "Morogrim Tidewalker", "Lady Vashj" },
                ["Hydross the Unstable"] = { 30056, 32516, 30050, 30055, 30047, 30054, 30048, 30053, 30052, 33055, 30664, 30629, 30049, 30051 },
                ["The Lurker Below"] = { 30064, 30067, 30062, 30060, 30066, 30065, 30057, 30059, 30061, 33054, 30665, 30063, 30058 },
                ["Leotheras the Blind"] = { 30092, 30097, 30091, 30096, 30627, 30095, 30239, 30240, 30241 },
                ["Fathom-Lord Karathress"] = { 30100, 30101, 30099, 30663, 30626, 30090, 30245, 30246, 30247 },
                ["Morogrim Tidewalker"] = { 30098, 30079, 30075, 30085, 30068, 30084, 30081, 30008, 30083, 33058, 30720, 30082, 30080 },
                ["Lady Vashj"] = { 30107, 30111, 30106, 30104, 30102, 30112, 30109, 30110, 30621, 30103, 30108, 30105, 30242, 30243, 30244, 29906 },
            },
            ["Tempest Keep"] = {
                _order = { "Al'ar", "Void Reaver", "High Astromancer Solarian", "Kael'thas Sunstrider" },
                ["Al'ar"] = { 29925, 29918, 29947, 29921, 29922, 29920, 30448, 30447, 29923, 32944, 29948, 29924, 29949 },
                ["Void Reaver"] = { 29986, 29984, 29985, 29983, 32515, 30619, 30450, 30248, 30249, 30250 },
                ["High Astromancer Solarian"] = { 29977, 29972, 29966, 29976, 29951, 29965, 29950, 32267, 30446, 30449, 29962, 29981, 29982 },
                ["Kael'thas Sunstrider"] = { 29992, 29989, 29994, 29990, 29987, 29995, 29991, 29998, 29997, 29993, 29996, 29988, 30236, 30237, 30238, 32458, 32405, 29905 },
            },
        },
    },
    ["P1"] = {
        raids = {
            ["Gruul's Lair"] = {
                _order = { "High King Maulgar", "Gruul the Dragonkiller" },
                ["High King Maulgar"] = { 28797, 28799, 28796, 28801, 28795, 28800, 29763, 29764, 29762 },
                ["Gruul the Dragonkiller"] = { 28804, 28803, 28828, 28827, 28810, 28824, 28822, 28823, 28830, 31750, 29766, 29767, 29765, 28802, 28794, 28825, 28826 },
            },
            ["Karazhan"] = {
                _order = { "Attumen the Huntsman", "Rokad the Ravager", "Shadikith the Glider", "Hyakiss the Lurker", "Moroes", "Maiden of Virtue", "Opera: The Wizard of Oz", "Opera: The Big Bad Wolf", "Opera: Romulo and Julianne", "The Curator", "Terestian Illhoof", "Shade of Aran", "Netherspite", "Chess Event", "Prince Malchezaar", "Nightbane", "Trash" },
                ["Attumen the Huntsman"] = { 28477, 28507, 28508, 28453, 28506, 28503, 28454, 28502, 28505, 28509, 28510, 28504, 30480, 23809 },
                ["Rokad the Ravager"] = { 30684, 30685, 30686, 30687 },
                ["Shadikith the Glider"] = { 30680, 30681, 30682, 30683 },
                ["Hyakiss the Lurker"] = { 30675, 30676, 30677, 30678 },
                ["Moroes"] = { 28529, 28570, 28565, 28545, 28567, 28566, 28569, 28530, 28528, 28525, 28568, 28524, 22559 },
                ["Maiden of Virtue"] = { 28511, 28515, 28517, 28514, 28521, 28520, 28519, 28512, 28518, 28516, 28523, 28522 },
                ["Opera: The Wizard of Oz"] = { 28586, 28585, 28587, 28588, 28594, 28591, 28589, 28593, 28590, 28592 },
                ["Opera: The Big Bad Wolf"] = { 28582, 28583, 28584, 28581, 28594, 28591, 28589, 28593, 28590, 28592 },
                ["Opera: Romulo and Julianne"] = { 28578, 28579, 28572, 28573, 28594, 28591, 28589, 28593, 28590, 28592 },
                ["The Curator"] = { 28612, 28647, 28631, 28621, 28649, 28633, 29757, 29758, 29756 },
                ["Terestian Illhoof"] = { 28660, 28653, 28652, 28654, 28655, 28656, 28662, 28661, 28785, 28657, 28658, 28659, 22561 },
                ["Shade of Aran"] = { 28672, 28726, 28670, 28663, 28669, 28671, 28666, 23933, 28674, 28675, 28727, 28728, 28673, 22560 },
                ["Netherspite"] = { 28744, 28742, 28732, 28741, 28735, 28740, 28743, 28733, 28731, 28730, 28734, 28729 },
                ["Chess Event"] = { 28756, 28755, 28750, 28752, 28751, 28746, 28748, 28747, 28745, 28753, 28749, 28754 },
                ["Prince Malchezaar"] = { 28765, 28766, 28764, 28762, 28763, 28757, 28770, 28768, 28767, 28773, 28771, 28772, 29760, 29761, 29759 },
                ["Nightbane"] = { 28602, 28600, 28601, 28599, 28610, 28597, 28608, 31751, 24139, 28609, 28603, 28604, 28611, 28606 },
                ["Trash"] = { 30642, 30668, 30673, 30644, 30674, 30643, 30641, 23857, 23864, 23862, 23865, 21882, 30666, 30667, 21903, 21904, 22545 },
            },
            ["Magtheridon's Lair"] = {
                _order = { "Magtheridon" },
                ["Magtheridon"] = { 28777, 28780, 28776, 28778, 28775, 28779, 28789, 28781, 28774, 28782, 29458, 28783, 29754, 29753, 29755 },
            },
            ["World Bosses"] = {
                _order = { "Doomwalker", "Doom Lord Kazzak" },
                ["Doomwalker"] = { 30729, 30725, 30727, 30730, 30728, 30731, 30726, 30723, 30722, 30724 },
                ["Doom Lord Kazzak"] = { 30735, 30734, 30737, 30739, 30740, 30741, 30736, 30738, 30733, 30732 },
            },
        },
    },
}
