-- ── LootCouncil EX — Data/Loot.lua ───────────────────────────────────────────
-- SHIPPED STATIC DATA — phase → raid → boss → {itemIDs}. GENERATED by tools/build_data.lua
-- from tools/sources/loot.csv — DO NOT EDIT BY HAND (your edits will be overwritten); edit
-- the CSV and re-run the converter.
--
-- Shape (PROJECT.md §6.6): Loot[phase].raids[raid][boss] = { itemID, ... }. Each raid also
-- carries an `_order` array giving boss kill order, honored by the DataAPI accessors.

local LCEX = LootCouncilEX

LCEX.Loot = {
    ["P2"] = {
        raids = {
            ["Serpentshrine Cavern"] = {
                _order = { "Hydross the Unstable", "The Lurker Below", "Leotheras the Blind", "Fathom-Lord Karathress", "Morogrim Tidewalker", "Lady Vashj" },
                ["Hydross the Unstable"] = { 30056, 32516, 30050, 30055, 30047, 30054, 30048, 30053, 30052, 33055, 30664, 30629, 30049, 30051 },
                ["The Lurker Below"] = { 30064, 30067, 30062, 30060, 30066, 30065, 30057, 30059, 30061, 33054, 30665, 30063, 30058 },
                ["Leotheras the Blind"] = { 30092, 30097, 30091, 30096, 30627, 30095, 30239, 30240, 30241 },
                ["Fathom-Lord Karathress"] = { 30100, 30101, 30099, 30663, 30626, 30090, 30245, 30246, 30247 },
                ["Morogrim Tidewalker"] = { 30098, 30079, 30075, 30085, 30068, 30084, 30081, 30008, 30083, 33058, 30720, 30082, 30080 },
                ["Lady Vashj"] = { 30107, 30111, 30106, 30104, 30102, 30112, 30109, 30110, 30621, 30103, 30108, 30105, 30242, 30243, 30244, 29906 },
            },
            ["Tempest Keep"] = {
                _order = { "Al'ar", "Void Reaver", "High Astromancer Solarian", "Kael'thas Sunstrider" },
                ["Al'ar"] = { 29925, 29918, 29947, 29921, 29922, 29920, 30448, 30447, 29923, 32944, 29948, 29924, 29949 },
                ["Void Reaver"] = { 29986, 29984, 29985, 29983, 32515, 30619, 30450, 30248, 30249, 30250 },
                ["High Astromancer Solarian"] = { 29977, 29972, 29966, 29976, 29951, 29965, 29950, 32267, 30446, 30449, 29962, 29981, 29982 },
                ["Kael'thas Sunstrider"] = { 29992, 29989, 29994, 29990, 29987, 29995, 29991, 29998, 29997, 29993, 29996, 29988, 30236, 30237, 30238, 32458, 32405, 29905 },
            },
        },
    },
}
