-- ── LootCouncil EX — Data/Prio.lua ───────────────────────────────────────────
-- SHIPPED STATIC DATA — per-item loot priority (§6.23). GENERATED by tools/build_data.lua
-- from tools/sources/prio.csv — DO NOT EDIT BY HAND.
--
-- Shape: Prio[itemID] = { { label = <str>, chain = { { text, ... }, ... } }, ... } — each
-- chain is an ordered list of rank-groups (equal-priority entries share a group).

local LCEX = LootCouncilEX

LCEX.Prio = {
}
