-- ── LootCouncil EX — Data/TierTokens.lua ─────────────────────────────────────
-- SHIPPED STATIC DATA — tier-token itemID → the per-class tier piece it turns into.
-- GENERATED by tools/build_data.lua from tools/sources/tokens.csv — DO NOT EDIT BY HAND.
--
-- Shape (PROJECT.md §6.6): TierTokens[tokenID] = { name = <display>, pieces = { CLASS = pieceID } }.

local LCEX = LootCouncilEX

LCEX.TierTokens = {
    [30236] = {
        name = "Chestguard of the Vanquished Champion",
        pieces = { ["ROGUE"] = true, ["SHAMAN"] = true, ["PALADIN"] = true },
    },
    [30237] = {
        name = "Chestguard of the Vanquished Defender",
        pieces = { ["DRUID"] = true, ["PRIEST"] = true, ["WARRIOR"] = true },
    },
    [30238] = {
        name = "Chestguard of the Vanquished Hero",
        pieces = { ["WARLOCK"] = true, ["HUNTER"] = true, ["MAGE"] = true },
    },
    [30239] = {
        name = "Gloves of the Vanquished Champion",
        pieces = { ["ROGUE"] = true, ["SHAMAN"] = true, ["PALADIN"] = true },
    },
    [30240] = {
        name = "Gloves of the Vanquished Defender",
        pieces = { ["DRUID"] = true, ["PRIEST"] = true, ["WARRIOR"] = true },
    },
    [30241] = {
        name = "Gloves of the Vanquished Hero",
        pieces = { ["WARLOCK"] = true, ["HUNTER"] = true, ["MAGE"] = true },
    },
    [30242] = {
        name = "Helm of the Vanquished Champion",
        pieces = { ["ROGUE"] = true, ["SHAMAN"] = true, ["PALADIN"] = true },
    },
    [30243] = {
        name = "Helm of the Vanquished Defender",
        pieces = { ["DRUID"] = true, ["PRIEST"] = true, ["WARRIOR"] = true },
    },
    [30244] = {
        name = "Helm of the Vanquished Hero",
        pieces = { ["WARLOCK"] = true, ["HUNTER"] = true, ["MAGE"] = true },
    },
    [30245] = {
        name = "Leggings of the Vanquished Champion",
        pieces = { ["ROGUE"] = true, ["SHAMAN"] = true, ["PALADIN"] = true },
    },
    [30246] = {
        name = "Leggings of the Vanquished Defender",
        pieces = { ["DRUID"] = true, ["PRIEST"] = true, ["WARRIOR"] = true },
    },
    [30247] = {
        name = "Leggings of the Vanquished Hero",
        pieces = { ["WARLOCK"] = true, ["HUNTER"] = true, ["MAGE"] = true },
    },
    [30248] = {
        name = "Pauldrons of the Vanquished Champion",
        pieces = { ["ROGUE"] = true, ["SHAMAN"] = true, ["PALADIN"] = true },
    },
    [30249] = {
        name = "Pauldrons of the Vanquished Defender",
        pieces = { ["DRUID"] = true, ["PRIEST"] = true, ["WARRIOR"] = true },
    },
    [30250] = {
        name = "Pauldrons of the Vanquished Hero",
        pieces = { ["WARLOCK"] = true, ["HUNTER"] = true, ["MAGE"] = true },
    },
}
