-- ── LootCouncil EX — Data/TierTokens.lua ─────────────────────────────────────
-- SHIPPED STATIC DATA — tier-token itemID → the per-class tier piece it turns into.
-- GENERATED by tools/build_data.lua from tools/sources/tokens.csv — DO NOT EDIT BY HAND.
--
-- Shape (PROJECT.md §6.6): TierTokens[tokenID] = { name = <display>, pieces = { CLASS = pieceID } }.

local LCEX = LootCouncilEX

LCEX.TierTokens = {
    [29753] = {
        name = "Chestguard of the Fallen Defender",
        pieces = { ["DRUID"] = { 29086, 29093, 29098 }, ["PRIEST"] = { 29049, 29058 }, ["WARRIOR"] = { 29011, 29021 } },
    },
    [29754] = {
        name = "Chestguard of the Fallen Champion",
        pieces = { ["PALADIN"] = { 29061, 29068, 29073 }, ["ROGUE"] = { 29044 }, ["SHAMAN"] = { 29028, 29035, 29040 } },
    },
    [29755] = {
        name = "Chestguard of the Fallen Hero",
        pieces = { ["HUNTER"] = { 29081 }, ["MAGE"] = { 29076 }, ["WARLOCK"] = { 28963 } },
    },
    [29756] = {
        name = "Gloves of the Fallen Hero",
        pieces = { ["HUNTER"] = { 29082 }, ["MAGE"] = { 29077 }, ["WARLOCK"] = { 28964 } },
    },
    [29757] = {
        name = "Gloves of the Fallen Champion",
        pieces = { ["PALADIN"] = { 29062, 29066, 29071 }, ["ROGUE"] = { 29045 }, ["SHAMAN"] = { 29029, 29033, 29038 } },
    },
    [29758] = {
        name = "Gloves of the Fallen Defender",
        pieces = { ["DRUID"] = { 29087, 29091, 29096 }, ["PRIEST"] = { 29050, 29056 }, ["WARRIOR"] = { 29012, 29019 } },
    },
    [29759] = {
        name = "Helm of the Fallen Hero",
        pieces = { ["HUNTER"] = { 29083 }, ["MAGE"] = { 29078 }, ["WARLOCK"] = { 28966 } },
    },
    [29760] = {
        name = "Helm of the Fallen Champion",
        pieces = { ["PALADIN"] = { 29063, 29069, 29074 }, ["ROGUE"] = { 29046 }, ["SHAMAN"] = { 29030, 29036, 29042 } },
    },
    [29761] = {
        name = "Helm of the Fallen Defender",
        pieces = { ["DRUID"] = { 29088, 29094, 29099 }, ["PRIEST"] = { 29053, 29059 }, ["WARRIOR"] = { 29015, 29022 } },
    },
    [29762] = {
        name = "Pauldrons of the Fallen Hero",
        pieces = { ["HUNTER"] = { 29085 }, ["MAGE"] = { 29080 }, ["WARLOCK"] = { 28968 } },
    },
    [29763] = {
        name = "Pauldrons of the Fallen Champion",
        pieces = { ["PALADIN"] = { 29065, 29067, 29072 }, ["ROGUE"] = { 29048 }, ["SHAMAN"] = { 29032, 29034, 29039 } },
    },
    [29764] = {
        name = "Pauldrons of the Fallen Defender",
        pieces = { ["DRUID"] = { 29090, 29092, 29097 }, ["PRIEST"] = { 29055, 29057 }, ["WARRIOR"] = { 29017, 29020 } },
    },
    [29765] = {
        name = "Leggings of the Fallen Hero",
        pieces = { ["HUNTER"] = { 29084 }, ["MAGE"] = { 29079 }, ["WARLOCK"] = { 28967 } },
    },
    [29766] = {
        name = "Leggings of the Fallen Champion",
        pieces = { ["PALADIN"] = { 29064, 29070, 29075 }, ["ROGUE"] = { 29047 }, ["SHAMAN"] = { 29031, 29037, 29043 } },
    },
    [29767] = {
        name = "Leggings of the Fallen Defender",
        pieces = { ["DRUID"] = { 29089, 29095, 29100 }, ["PRIEST"] = { 29054, 29060 }, ["WARRIOR"] = { 29016, 29023 } },
    },
    [30236] = {
        name = "Chestguard of the Vanquished Champion",
        pieces = { ["ROGUE"] = { 30144 }, ["SHAMAN"] = { 30164, 30169, 30185 }, ["PALADIN"] = { 30134, 30123, 30129 } },
    },
    [30237] = {
        name = "Chestguard of the Vanquished Defender",
        pieces = { ["DRUID"] = { 30222, 30216, 30231 }, ["PRIEST"] = { 30150, 30159 }, ["WARRIOR"] = { 30113, 30118 } },
    },
    [30238] = {
        name = "Chestguard of the Vanquished Hero",
        pieces = { ["WARLOCK"] = { 30214 }, ["HUNTER"] = { 30139 }, ["MAGE"] = { 30196 } },
    },
    [30239] = {
        name = "Gloves of the Vanquished Champion",
        pieces = { ["ROGUE"] = { 30145 }, ["SHAMAN"] = { 30165, 30170, 30189 }, ["PALADIN"] = { 30135, 30124, 30130 } },
    },
    [30240] = {
        name = "Gloves of the Vanquished Defender",
        pieces = { ["DRUID"] = { 30223, 30217, 30232 }, ["PRIEST"] = { 30151, 30160 }, ["WARRIOR"] = { 30114, 30119 } },
    },
    [30241] = {
        name = "Gloves of the Vanquished Hero",
        pieces = { ["WARLOCK"] = { 30211 }, ["HUNTER"] = { 30140 }, ["MAGE"] = { 30205 } },
    },
    [30242] = {
        name = "Helm of the Vanquished Champion",
        pieces = { ["ROGUE"] = { 30146 }, ["SHAMAN"] = { 30166, 30171, 30190 }, ["PALADIN"] = { 30136, 30125, 30131 } },
    },
    [30243] = {
        name = "Helm of the Vanquished Defender",
        pieces = { ["DRUID"] = { 30228, 30219, 30233 }, ["PRIEST"] = { 30152, 30161 }, ["WARRIOR"] = { 30115, 30120 } },
    },
    [30244] = {
        name = "Helm of the Vanquished Hero",
        pieces = { ["WARLOCK"] = { 30212 }, ["HUNTER"] = { 30141 }, ["MAGE"] = { 30206 } },
    },
    [30245] = {
        name = "Leggings of the Vanquished Champion",
        pieces = { ["ROGUE"] = { 30148 }, ["SHAMAN"] = { 30167, 30172, 30192 }, ["PALADIN"] = { 30137, 30126, 30132 } },
    },
    [30246] = {
        name = "Leggings of the Vanquished Defender",
        pieces = { ["DRUID"] = { 30229, 30220, 30234 }, ["PRIEST"] = { 30153, 30162 }, ["WARRIOR"] = { 30116, 30121 } },
    },
    [30247] = {
        name = "Leggings of the Vanquished Hero",
        pieces = { ["WARLOCK"] = { 30213 }, ["HUNTER"] = { 30142 }, ["MAGE"] = { 30207 } },
    },
    [30248] = {
        name = "Pauldrons of the Vanquished Champion",
        pieces = { ["ROGUE"] = { 30149 }, ["SHAMAN"] = { 30168, 30173, 30194 }, ["PALADIN"] = { 30138, 30127, 30133 } },
    },
    [30249] = {
        name = "Pauldrons of the Vanquished Defender",
        pieces = { ["DRUID"] = { 30230, 30221, 30235 }, ["PRIEST"] = { 30154, 30163 }, ["WARRIOR"] = { 30117, 30122 } },
    },
    [30250] = {
        name = "Pauldrons of the Vanquished Hero",
        pieces = { ["WARLOCK"] = { 30215 }, ["HUNTER"] = { 30143 }, ["MAGE"] = { 30210 } },
    },
}
