-- ── LootCouncil EX — tools/build_data.lua ────────────────────────────────────
-- DEV-TIME converter (NOT shipped — excluded via .pkgmeta). Turns the human-verifiable CSV
-- sources under tools/sources/ into the canonical Core/Data/*.lua tables, so the shipped data
-- has a single reviewable source of truth and adding a phase is a CSV edit + a re-run, never
-- hand-editing nested Lua. Runs in the same standalone Lua 5.1 as the test harness:
--
--     lua tools/build_data.lua          # regenerate Core/Data/Loot.lua + TierTokens.lua
--     lua tools/build_data.lua --check  # exit non-zero if the committed Lua is out of date
--
-- CSV shapes (header row required; '#'-prefixed lines and blank lines are ignored):
--   sources/loot.csv    phase,raid,order,boss,itemID    (one item per row; order = boss kill order)
--   sources/tokens.csv  tokenID,name,class,pieceID       (one class-piece per row)

local ROOT = (arg[0] or "tools/build_data.lua"):gsub("[/\\]tools[/\\]build_data%.lua$", "")
if ROOT == arg[0] then ROOT = "." end

-- ── CSV ───────────────────────────────────────────────────────────────────────
local function split(line)
    local out = {}
    for field in (line .. ","):gmatch("([^,]*),") do
        out[#out + 1] = (field:gsub("^%s*(.-)%s*$", "%1"))
    end
    return out
end

-- Read a CSV into a list of {header=value} rows. First non-comment line is the header.
local function readCSV(path)
    local f = assert(io.open(path, "r"), "cannot open " .. path)
    local header, rows = nil, {}
    for line in f:lines() do
        line = line:gsub("\r$", "")
        if line ~= "" and line:sub(1, 1) ~= "#" then
            local fields = split(line)
            if not header then
                header = fields
            else
                local row = {}
                for i, h in ipairs(header) do row[h] = fields[i] end
                rows[#rows + 1] = row
            end
        end
    end
    f:close()
    return rows
end

-- ── Emit helpers ───────────────────────────────────────────────────────────────
local function writeIfChanged(path, text, check)
    local existing
    local f = io.open(path, "r")
    if f then existing = f:read("*a"); f:close() end
    if existing == text then return false end
    if check then
        io.stderr:write("OUT OF DATE: " .. path .. " — run `lua tools/build_data.lua`\n")
        return true
    end
    local out = assert(io.open(path, "w"), "cannot write " .. path)
    out:write(text)
    out:close()
    print("wrote " .. path)
    return false
end

-- ── Loot.lua ───────────────────────────────────────────────────────────────────
local function buildLoot()
    local rows = readCSV(ROOT .. "/tools/sources/loot.csv")
    -- phase -> raid -> { order = {boss->n}, bosses = {boss->{itemIDs}}, raidOrder for stable raids }
    local phases, phaseSeen = {}, {}
    local tree = {}
    for _, r in ipairs(rows) do
        local phase, raid, boss = r.phase, r.raid, r.boss
        local order, itemID = tonumber(r.order), tonumber(r.itemID)
        assert(phase and raid and boss and order and itemID,
            "bad loot row: " .. (r.phase or "?") .. "/" .. (r.raid or "?") .. "/" .. (r.boss or "?"))
        if not phaseSeen[phase] then phaseSeen[phase] = true; phases[#phases + 1] = phase end
        tree[phase] = tree[phase] or {}
        tree[phase][raid] = tree[phase][raid] or { bossOrder = {}, bossSeen = {}, items = {} }
        local rd = tree[phase][raid]
        if not rd.bossSeen[boss] then
            rd.bossSeen[boss] = order
            rd.bossOrder[#rd.bossOrder + 1] = boss
            rd.items[boss] = {}
        end
        table.insert(rd.items[boss], itemID)
    end

    local out = {}
    local function w(s) out[#out + 1] = s end
    w("-- ── LootCouncil EX — Data/Loot.lua ───────────────────────────────────────────")
    w("-- SHIPPED STATIC DATA — phase → raid → boss → {itemIDs}. GENERATED by tools/build_data.lua")
    w("-- from tools/sources/loot.csv — DO NOT EDIT BY HAND (your edits will be overwritten); edit")
    w("-- the CSV and re-run the converter.")
    w("--")
    w("-- Shape (PROJECT.md §6.6): Loot[phase].raids[raid][boss] = { itemID, ... }. Each raid also")
    w("-- carries an `_order` array giving boss kill order, honored by the DataAPI accessors.")
    w("")
    w("local LCEX = LootCouncilEX")
    w("")
    w("LCEX.Loot = {")
    for _, phase in ipairs(phases) do
        w(string.format("    [%q] = {", phase))
        w("        raids = {")
        local raids = {}
        for raid in pairs(tree[phase]) do raids[#raids + 1] = raid end
        table.sort(raids)
        for _, raid in ipairs(raids) do
            local rd = tree[phase][raid]
            -- bosses sorted by their kill-order number, stable.
            table.sort(rd.bossOrder, function(a, b) return rd.bossSeen[a] < rd.bossSeen[b] end)
            w(string.format("            [%q] = {", raid))
            local quoted = {}
            for _, b in ipairs(rd.bossOrder) do quoted[#quoted + 1] = string.format("%q", b) end
            w("                _order = { " .. table.concat(quoted, ", ") .. " },")
            for _, boss in ipairs(rd.bossOrder) do
                w(string.format("                [%q] = { %s },", boss, table.concat(rd.items[boss], ", ")))
            end
            w("            },")
        end
        w("        },")
        w("    },")
    end
    w("}")
    w("")
    return table.concat(out, "\n")
end

-- ── TierTokens.lua ───────────────────────────────────────────────────────────
local function buildTokens()
    local rows = readCSV(ROOT .. "/tools/sources/tokens.csv")
    local order, seen, tokens = {}, {}, {}
    for _, r in ipairs(rows) do
        -- pieces[CLASS] is a LIST: a class with spec-variant tier sets (paladin/shaman/druid/
        -- warrior/priest) redeems one token into several possible items, so each (token,class)
        -- piece is its own CSV row and they accumulate in first-seen order.
        local id, class, piece = tonumber(r.tokenID), r.class, tonumber(r.pieceID)
        assert(id and r.name and class and piece, "bad token row: " .. (r.tokenID or "?"))
        if not seen[id] then seen[id] = true; order[#order + 1] = id; tokens[id] = { name = r.name, pieces = {}, pieceOrder = {} } end
        local t = tokens[id]
        if not t.pieces[class] then t.pieces[class] = {}; t.pieceOrder[#t.pieceOrder + 1] = class end
        local list = t.pieces[class]
        list[#list + 1] = piece
    end
    table.sort(order)

    local out = {}
    local function w(s) out[#out + 1] = s end
    w("-- ── LootCouncil EX — Data/TierTokens.lua ─────────────────────────────────────")
    w("-- SHIPPED STATIC DATA — tier-token itemID → the per-class tier piece it turns into.")
    w("-- GENERATED by tools/build_data.lua from tools/sources/tokens.csv — DO NOT EDIT BY HAND.")
    w("--")
    w("-- Shape (PROJECT.md §6.6): TierTokens[tokenID] = { name = <display>, pieces = { CLASS = pieceID } }.")
    w("")
    w("local LCEX = LootCouncilEX")
    w("")
    w("LCEX.TierTokens = {")
    for _, id in ipairs(order) do
        local t = tokens[id]
        w(string.format("    [%d] = {", id))
        w(string.format("        name = %q,", t.name))
        local parts = {}
        for _, class in ipairs(t.pieceOrder) do
            parts[#parts + 1] = string.format("[%q] = { %s }", class, table.concat(t.pieces[class], ", "))
        end
        w("        pieces = { " .. table.concat(parts, ", ") .. " },")
        w("    },")
    end
    w("}")
    w("")
    return table.concat(out, "\n")
end

-- ── BiS.lua ────────────────────────────────────────────────────────────────────
-- BiS[CLASS][spec][phase][slot] = { itemID, altID, ... }. Validates class/spec/slot against the
-- fixed TBC taxonomy (hardcoded here since the tool runs outside the addon). CONTENT is opinion
-- data filled in a content pass; the pipeline works with whatever rows bis.csv holds (incl. none).
local BIS_SLOTS = { head = true, neck = true, shoulder = true, back = true, chest = true,
    wrist = true, hands = true, waist = true, legs = true, feet = true, finger = true,
    trinket = true, mainhand = true, offhand = true, ranged = true }
local CLASS_SPECS = {
    WARRIOR = { Arms = 1, Fury = 1, Protection = 1 },
    PALADIN = { Holy = 1, Protection = 1, Retribution = 1 },
    HUNTER  = { ["Beast Mastery"] = 1, Marksmanship = 1, Survival = 1 },
    ROGUE   = { Assassination = 1, Combat = 1, Subtlety = 1 },
    PRIEST  = { Discipline = 1, Holy = 1, Shadow = 1 },
    SHAMAN  = { Elemental = 1, Enhancement = 1, Restoration = 1 },
    MAGE    = { Arcane = 1, Fire = 1, Frost = 1 },
    WARLOCK = { Affliction = 1, Demonology = 1, Destruction = 1 },
    DRUID   = { Balance = 1, Feral = 1, Restoration = 1 },
}

local function buildBiS()
    local rows = readCSV(ROOT .. "/tools/sources/bis.csv")
    -- class -> {specOrder, specs = spec -> {phaseOrder, phases = phase -> {slotOrder, slots = slot->{ids}}}}
    local classOrder, tree = {}, {}
    for _, r in ipairs(rows) do
        local class, spec, phase, slot = r.class, r.spec, r.phase, r.slot
        local itemID = tonumber(r.itemID)
        assert(class and CLASS_SPECS[class], "bad BiS class: " .. tostring(class))
        assert(spec and CLASS_SPECS[class][spec], "bad BiS spec: " .. tostring(class) .. "/" .. tostring(spec))
        assert(slot and BIS_SLOTS[slot], "bad BiS slot: " .. tostring(slot))
        assert(itemID, "bad BiS itemID for " .. class .. "/" .. spec .. "/" .. (phase or "?"))
        if not tree[class] then classOrder[#classOrder + 1] = class
            tree[class] = { specOrder = {}, specs = {} } end
        local c = tree[class]
        if not c.specs[spec] then c.specOrder[#c.specOrder + 1] = spec
            c.specs[spec] = { phaseOrder = {}, phases = {} } end
        local s = c.specs[spec]
        if not s.phases[phase] then s.phaseOrder[#s.phaseOrder + 1] = phase
            s.phases[phase] = { slotOrder = {}, slots = {} } end
        local p = s.phases[phase]
        if not p.slots[slot] then p.slotOrder[#p.slotOrder + 1] = slot; p.slots[slot] = {} end
        table.insert(p.slots[slot], itemID)
    end

    local out = {}
    local function w(s) out[#out + 1] = s end
    w("-- ── LootCouncil EX — Data/BiS.lua ────────────────────────────────────────────")
    w("-- SHIPPED STATIC DATA — class → spec → phase → slot → {itemIDs}. GENERATED by")
    w("-- tools/build_data.lua from tools/sources/bis.csv — DO NOT EDIT BY HAND.")
    w("--")
    w("-- Shape (PROJECT.md §6.6): BiS[CLASS][spec][phase][slot] = { itemID, altID, ... }.")
    w("")
    w("local LCEX = LootCouncilEX")
    w("")
    w("LCEX.BiS = {")
    table.sort(classOrder)
    for _, class in ipairs(classOrder) do
        local c = tree[class]
        w(string.format("    [%q] = {", class))
        table.sort(c.specOrder)
        for _, spec in ipairs(c.specOrder) do
            local s = c.specs[spec]
            w(string.format("        [%q] = {", spec))
            table.sort(s.phaseOrder)
            for _, phase in ipairs(s.phaseOrder) do
                local p = s.phases[phase]
                w(string.format("            [%q] = {", phase))
                for _, slot in ipairs(p.slotOrder) do
                    w(string.format("                %s = { %s },", slot, table.concat(p.slots[slot], ", ")))
                end
                w("            },")
            end
            w("        },")
        end
        w("    },")
    end
    w("}")
    w("")
    return table.concat(out, "\n")
end

-- ── Prio.lua ───────────────────────────────────────────────────────────────────
-- Prio[itemID] = { { label = <chainLabel>, chain = { { text, ... }, ... } }, ... }. Each chain is
-- an ordered list of RANK-GROUPS; equal-rank rows share a group (the sheet's `A = B > C`). CSV row:
--   sources/prio.csv   itemID,chainLabel,rank,text
local function buildPrio()
    local rows = readCSV(ROOT .. "/tools/sources/prio.csv")
    local itemOrder, items = {}, {}
    for _, r in ipairs(rows) do
        local itemID, rank, text = tonumber(r.itemID), tonumber(r.rank), r.text
        local label = r.chainLabel or "Main"
        assert(itemID and rank and text and text ~= "",
            "bad prio row: " .. (r.itemID or "?") .. "/" .. (r.chainLabel or "?"))
        if not items[itemID] then itemOrder[#itemOrder + 1] = itemID
            items[itemID] = { chainOrder = {}, chains = {} } end
        local it = items[itemID]
        if not it.chains[label] then it.chainOrder[#it.chainOrder + 1] = label
            it.chains[label] = { rankOrder = {}, ranks = {} } end
        local ch = it.chains[label]
        if not ch.ranks[rank] then ch.rankOrder[#ch.rankOrder + 1] = rank; ch.ranks[rank] = {} end
        table.insert(ch.ranks[rank], text)
    end

    local out = {}
    local function w(s) out[#out + 1] = s end
    w("-- ── LootCouncil EX — Data/Prio.lua ───────────────────────────────────────────")
    w("-- SHIPPED STATIC DATA — per-item loot priority (§6.23). GENERATED by tools/build_data.lua")
    w("-- from tools/sources/prio.csv — DO NOT EDIT BY HAND.")
    w("--")
    w("-- Shape: Prio[itemID] = { { label = <str>, chain = { { text, ... }, ... } }, ... } — each")
    w("-- chain is an ordered list of rank-groups (equal-priority entries share a group).")
    w("")
    w("local LCEX = LootCouncilEX")
    w("")
    w("LCEX.Prio = {")
    table.sort(itemOrder)
    for _, itemID in ipairs(itemOrder) do
        local it = items[itemID]
        w(string.format("    [%d] = {", itemID))
        for _, label in ipairs(it.chainOrder) do
            local ch = it.chains[label]
            table.sort(ch.rankOrder)
            local groups = {}
            for _, rank in ipairs(ch.rankOrder) do
                local quoted = {}
                for _, txt in ipairs(ch.ranks[rank]) do quoted[#quoted + 1] = string.format("%q", txt) end
                groups[#groups + 1] = "{ " .. table.concat(quoted, ", ") .. " }"
            end
            w(string.format("        { label = %q, chain = { %s } },", label, table.concat(groups, ", ")))
        end
        w("    },")
    end
    w("}")
    w("")
    return table.concat(out, "\n")
end

-- ── Main ───────────────────────────────────────────────────────────────────────
local check = (arg[1] == "--check")
local stale = false
stale = writeIfChanged(ROOT .. "/Core/Data/Loot.lua", buildLoot(), check) or stale
stale = writeIfChanged(ROOT .. "/Core/Data/TierTokens.lua", buildTokens(), check) or stale
stale = writeIfChanged(ROOT .. "/Core/Data/BiS.lua", buildBiS(), check) or stale
stale = writeIfChanged(ROOT .. "/Core/Data/Prio.lua", buildPrio(), check) or stale
if check and stale then os.exit(1) end
